name: Echidna lws-authn-ssi-cid
on:
  pull_request:
    paths: 
      - "lws10-authn-ssi-cid/**"
  push:
    branches: [main]
    paths: 
      - "lws10-authn-ssi-cid/**"
jobs:
  main:
    name: Build, validate and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: lws10-authn-ssi-cid/index.html
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_AUTHN_SSI_CID }}
          W3C_WG_DECISION_URL: https://www.w3.org/2026/04/28-lws-minutes.html#0c16
          W3C_BUILD_OVERRIDE: |
             shortName: lws10-authn-ssi-cid
             specStatus: WD
